name: Release Reframe

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (skip release)'
        required: false
        type: boolean
        default: false

jobs:
  release:
    uses: GoPlasmatic/devops/.github/workflows/rust-release-reusable.yml@main
    with:
      repository: GoPlasmatic/Reframe
      package-type: application
      skip-publish: true  # Reframe is not published to crates.io
      dry-run: ${{ inputs.dry_run }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}