name: Release dataflow-rs

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (skip crates.io publish)'
        required: false
        type: boolean
        default: false

jobs:
  release:
    uses: GoPlasmatic/devops/.github/workflows/rust-release-reusable.yml@main
    with:
      repository: GoPlasmatic/dataflow-rs
      package-type: library
      dry-run: ${{ inputs.dry_run }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}